services:
  db:
    image: postgres:16
    container_name: ZTI-wsp-postgres
    environment:
      POSTGRES_DB: wsp_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ZTI-wsp-backend
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/wsp_db
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      JWT_SECRET: zti-wsp-jakub-galka-secret-key-2026-minimum-32-chars
    ports:
      - "8080:8080"

volumes:
  postgres_data:
